services:
  db:  # THIS IS THE MISSING PIECE
    image: postgres:15
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 # ADD THIS LINE
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: